# Generated by Django 4.0.5 on 2022-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_course',
            field=models.CharField(max_length=255),
        ),
    ]
