# Generated by Django 4.0.5 on 2022-08-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_s_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='Courses',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
