# Generated by Django 4.0.5 on 2022-08-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_courses_table_alter_students_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='s_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses'),
        ),
    ]
