# Generated by Django 4.0.5 on 2022-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_students_s_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile_num',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
