# Generated by Django 4.0.5 on 2022-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_students_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
