# Generated by Django 4.0.5 on 2022-08-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_students_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='fees',
        ),
    ]
