# Generated by Django 4.0.5 on 2022-08-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_students_duration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
